spring.application.name=legacy-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/legacydb
spring.datasource.username=legacyuser
spring.datasource.password=password

spring.sql.init.mode=always